# Generated by Django 3.0.3 on 2020-03-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese los nombres (p. ej. Juan Antonio.)', max_length=40)),
                ('apellido', models.CharField(help_text='Ingrese los apellidos (p. ej. Chavez Linares.)', max_length=40)),
                ('dni', models.CharField(help_text='Ingrese el DNI de la persona.)', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('matriculado', models.CharField(max_length=1)),
                ('nivel', models.CharField(max_length=10)),
                ('anhio', models.CharField(max_length=1)),
                ('seccion', models.CharField(max_length=1)),
                ('condicionfisica', models.CharField(max_length=1000)),
                ('obs_docente', models.CharField(max_length=10000)),
                ('obs_asistentesocial', models.CharField(max_length=10000)),
                ('fecha', models.DateField()),
                ('id_persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Persona')),
            ],
        ),
    ]
