# Generated by Django 3.0.3 on 2020-03-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(help_text='Ingrese los apellidos)', max_length=80),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(help_text='Ingrese los nombres', max_length=80),
        ),
    ]
