# Generated by Django 3.0.3 on 2020-03-10 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200310_1853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='CPersona',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
