# Generated by Django 3.0.3 on 2020-03-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200310_2118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CPersona',
            new_name='Persona',
        ),
    ]
