# Generated by Django 3.0.3 on 2020-03-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200310_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese los nombres', max_length=80)),
                ('apellido', models.CharField(help_text='Ingrese los apellidos', max_length=80)),
                ('dni', models.CharField(help_text='Ingrese el DNI de la persona.)', max_length=10)),
                ('condicion', models.CharField(help_text='Ingrese la afeccion del alumno', max_length=250)),
                ('obs_docente', models.CharField(help_text='Ingrese las observaciones del alumno', max_length=300)),
                ('obs_asistente', models.CharField(help_text='Ingrese las observaciones del alumno', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
