# Generated by Django 3.0.3 on 2020-03-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200310_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='anhio',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1),
        ),
        migrations.AddField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nivel',
            field=models.CharField(blank=True, choices=[('Inicial', 'Inicial'), ('Primnaria', 'Primnaria'), ('Secundaria', 'Secundaria')], max_length=10),
        ),
        migrations.AddField(
            model_name='alumno',
            name='seccion',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1),
        ),
    ]
