# Generated by Django 3.0.3 on 2020-03-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200311_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='obs_asistente',
            field=models.CharField(blank=True, help_text='Ingrese las observaciones del alumno', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='obs_docente',
            field=models.CharField(blank=True, help_text='Ingrese las observaciones del alumno', max_length=300, null=True),
        ),
    ]
