# Generated by Django 3.0.3 on 2020-03-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200311_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='obs_asistente',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='obs_docente',
        ),
    ]
